<div class="page-header">
	<h1>Hi User</h1>
</div>

<div class="row">
	<div class="col-4">
		<div class="list-group">
			<a href="<?= $this->url->get('admin') ?>" class="list-group-item list-group-item-action active">
				home
			</a>
			<a href="<?= $this->url->get('admin/news') ?>" class="list-group-item list-group-item-action">News</a>
			<a href="<?= $this->url->get('admin/users') ?>" class="list-group-item list-group-item-action">Users</a>
			<a href="<?= $this->url->get('admin/exit') ?>" class="list-group-item list-group-item-action">Exit</a>
		</div>
	</div>
	<div class="col-8">
		<div class="card" style="width: 18rem;">
			<img src="..." class="card-img-top" alt="...">
			<div class="card-body">
				<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
			</div>
		</div>
		<div class="card" style="width: 18rem;">
			<img src="..." class="card-img-top" alt="...">
			<div class="card-body">
				<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
			</div>
		</div>
		<div class="card" style="width: 18rem;">
			<img src="..." class="card-img-top" alt="...">
			<div class="card-body">
				<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
			</div>
		</div>
		<div class="card" style="width: 18rem;">
			<img src="..." class="card-img-top" alt="...">
			<div class="card-body">
				<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
			</div>
		</div>
	</div>
</div>