<?php if ($users->count() > 0): ?>
	<table class="table table-bordered table-hover">
		<thead class="thead-light">
		<tr>
			<th>#</th>
			<th>Name</th>
			<th>Email</th>
		</tr>
		</thead>
		<tfoot>
		<tr>
			<td colspan="3">Users quantity: <?php echo $users->count(); ?></td>
		</tr>
		</tfoot>
		<tbody>
		<?php foreach ($users as $user) { ?>
			<tr>
				<td><?php echo $user->id; ?></td>
				<td><?php echo $user->name; ?></td>
				<td><?php echo $user->email; ?></td>
			</tr>
		<?php } ?>
		</tbody>
	</table>
<?php else: ?>
	<div class="alert alert-danger">
		Table users is empty
	</div>
<?php endif; ?>