<div class="page-header">
	<h1>Hi User</h1>
</div>

<div class="row">
	<div class="col-4">
		<div class="list-group">
			<a href="<?= $this->url->get('admin') ?>" class="list-group-item list-group-item-action active">
				home
			</a>
			<a href="<?= $this->url->get('admin/news') ?>" class="list-group-item list-group-item-action">News</a>
			<a href="<?= $this->url->get('admin/users') ?>" class="list-group-item list-group-item-action">Users</a>
			<a href="<?= $this->url->get('admin/exit') ?>" class="list-group-item list-group-item-action">Exit</a>
		</div>
	</div>
	<div class="col-8">
		<?php if ($users->count() > 0): ?>
			<table class="table table-bordered table-hover">
				<thead class="thead-light">
				<tr>
					<th>#</th>
					<th>Name</th>
					<th>Email</th>
				</tr>
				</thead>
				<tfoot>
				<tr>
					<td colspan="3">Users quantity: <?php echo $users->count(); ?></td>
				</tr>
				</tfoot>
				<tbody>
				<?php foreach ($users as $user) { ?>
					<tr>
						<td><?php echo $user->id; ?></td>
						<td><?php echo $user->name; ?></td>
						<td><?php echo $user->email; ?></td>
					</tr>
				<?php } ?>
				</tbody>
			</table>
		<?php else: ?>
			<div class="alert alert-danger">
				Table users is empty
			</div>
		<?php endif; ?>
	</div>
</div>